# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-15 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automationUI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ate_proceedtosubmitflag',
            name='RequestTime',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
