# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-15 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automationUI', '0002_auto_20170815_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ate_proceedtosubmitflag',
            name='ExecuteCounter',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
