# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-15 05:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automationUI', '0003_auto_20170815_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ate_quoteapprovals',
            old_name='MailTo',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='ate_rmdata',
            old_name='MailTo',
            new_name='Email',
        ),
    ]
